Dump load
IdentityPython/idpy-oidc pull request #101
Opened 2024-04-27 09:49 UTC by rohe

The dump/load methods used for persistence storage of state was not working well in the general case.
This PR fixes that

2024-05-14 09:22 UTC, rohe commented
@lionick and @peppelinux I really would like to have your reviews.

2024-05-15 10:26 UTC, peppelinux requested changes
I didn't have time to test it with satosa-oidcop but it seems formally good, I just have added a quick suggestion to reduce the hadoken code

2024-05-15 10:26 UTC, peppelinux commented on src/idpyoidc/impexp.py
> +
```suggestion
                if not target_val:
                    continue
                    
                if param in _cls_init_args and param not in _kwargs:
                    if not _kwargs["init_args"]:
                        _kwargs["init_args"] = {param: target_val}
                    else:
                        _kwargs["init_args"][param] = target_val

```

2024-05-22 06:36 UTC, lionick approved these changes
Running my tests at oidc frontend, I can confirm that everything works as expected.

2024-05-24 08:01 UTC, rohe commented
Completely baffled. Checks fail on a test that is not part of the package ?!

2024-05-24 08:03 UTC, merged